version: '3'

services:
  sshd:
    image: endoffight/alpine-with-sshd
    environment:
      ROOT_PASS: "${ROOT_PASS:-phpgao}"
    container_name: alpine-sshd
    restart: on-failure
    ports:
      - "54322:22"
    logging:
      options:
        max-size: '1m'
        max-file: '1'
      driver: json-file
