name: trojan_go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./trojan-go
          push: true
          tags: endoffight/trojan-go:${{ steps.vars.outputs.sha_short }},endoffight/trojan-go:latest

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./trojan-go
          push: true
          tags: endoffight/scrapy-go:${{ steps.vars.outputs.sha_short }},endoffight/scrapy-go:latest
